# Generated by Django 2.0.5 on 2018-09-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vmms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carModel', models.CharField(max_length=255)),
                ('VIN', models.CharField(max_length=17)),
                ('mileage', models.IntegerField()),
                ('recipient', models.CharField(max_length=5)),
                ('sampleDate', models.DateTimeField()),
                ('returnDate', models.DateTimeField()),
                ('testProject', models.IntegerField()),
                ('testState', models.IntegerField()),
                ('transport', models.IntegerField()),
                ('park', models.IntegerField()),
                ('remarks', models.TextField()),
            ],
        ),
    ]
