# Generated by Django 2.0.5 on 2018-09-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmms',
            name='park',
            field=models.IntegerField(default=0, verbose_name=((0, '试验室'), (1, '停车场'))),
        ),
    ]
